logging:
  level:
    com:
      bing: error
    root: error
spring:
  jpa:
    show-sql: false
    
server:
  ssl:
    key-store: classpath:cert.p12
    key-store-password: 123321...
    key-store-type: PKCS12
    key-alias: 1